# Perfil de producción
spring.thymeleaf.cache=true
server.error.include-message=never
server.error.include-stacktrace=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
